import Head from "next/head";
import TimeLine from "./components/TimeLine";

export default function Home() {
  return (
    <>
      <Head>
        <title>SNS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <TimeLine />
      </div>
    </>
  );
}
